export enum RestrictionEnum {
    NO_MAX_ASSIGNMENTS_PER_TEACHER='NO_MAX_ASSIGNMENTS_PER_TEACHER',
    NO_PERIODS_FOR_LUNCH='NO_PERIODS_FOR_LUNCH',
    SCHEDULE_START_TIME='SCHEDULE_START_TIME',
    SCHEDULE_END_TIME='SCHEDULE_END_TIME',
    PERIODS_DURATION='PERIODS_DURATION',
    MAX_NUMBER_OF_STUDENTS_PER_CLASS='MAX_NUMBER_OF_STUDENTS_PER_CLASS',
    MIN_NUMBER_OF_STUDENTS_PER_CLASS='MIN_NUMBER_OF_STUDENTS_PER_CLASS',
}